[tool.black]
line-length=120

[tool.pylint.'MESSAGES CONTROL']
max-line-length = 120
disable = 'missing-class-docstring,missing-module-docstring,missing-function-docstring'

[tool.pytest.ini_options]
markers = [
    'unit',
    'integration',
    'functional',
    'slow',
    'flaky'
]


