"""empty message

Revision ID: fd8ba209db5d
Revises: 96559f8a62ad
Create Date: 2023-01-13 11:05:56.386884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd8ba209db5d'
down_revision = '96559f8a62ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offer', 'repository_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('offer', 'code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.create_unique_constraint(None, 'offer', ['repository_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offer', type_='unique')
    op.alter_column('offer', 'code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('offer', 'repository_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
